<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20240211132952 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Adding quiz_snapshot table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE quiz_snapshot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, data JSONB NOT NULL, quiz_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FA89EC70853CD175 ON quiz_snapshot (quiz_id)');
        $this->addSql('ALTER TABLE quiz_snapshot ADD CONSTRAINT FK_FA89EC70853CD175 FOREIGN KEY (quiz_id) REFERENCES quiz (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE quiz_snapshot DROP CONSTRAINT FK_FA89EC70853CD175');
        $this->addSql('DROP TABLE quiz_snapshot');
    }
}
